---
version: "3.9"
services:
  sui:
    image: mysten/sui-node:mainnet
    container_name: sui
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9184:9184"
    expose:
      - "9000"
      - "9184"
    restart: always
    #environment:
    #  - RUST_LOG=info,sui_core=debug
    volumes:
      - ./config.yml:/sui/fullnode.yaml:ro
      - ./genesis.blob:/sui/genesis.blob:ro
      - ./suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb:
